#!/bin/bash
###############################################################################
# Perform a check and report to CHECKLOGFILE
# WARNING:
# The CHECKLOGFILE file must not be created unless the check really unveiled
# a problem.

# Print to stderr if CHECKLOGFILE is not defined yet (e.g. as the script is
# not called from oarnodecheckcron the CHECKLOGFILE environment variable is
# not defined)
[ -n "$CHECKLOGFILE" ] || CHECKLOGFILE=/dev/stderr

###############################################################################
# YOUR CHECK SCRIPT GOES BELOW

# Example of check: does the oar user exist ?
id oar >& /dev/null || "OAR user not found on the system)" > $CHECKLOGFILE
