LIBS=unix
PACKS=mysql
SOURCES= ../simple_cbf/interval.ml helpers.ml conf.ml types.ml iolib.ml ../simple_cbf/simple_cbf.ml simple_cbf_oar.ml
RESULT=simple_cbf_oar

-include OCamlMakefile

install:  $(RESULT) 
	cp $(RESULT) /usr/lib/oar/

