#!/usr/bin/perl
#Hold a job --> it will not be scheduled

use strict;
use warnings;
use Data::Dumper;
use DBI();
use oar_iolib;
use oar_conflib qw(init_conf dump_conf get_conf is_conf);
use oar_Tools;

sub usage {
    print STDERR "usage: qhold [idJob]\n";
    exit 1;
}

init_conf("oar.conf");
my $remote_host = get_conf("SERVER_HOSTNAME");
my $remote_port = get_conf("SERVER_PORT");

usage if (@ARGV < 1);

my $idJob = $ARGV[0];
print "idJob = $idJob\n";

my $base = iolib::connect();
my $err = iolib::hold_job($base,$idJob);
iolib::disconnect($base);

if ($err != 0) {
    print STDERR "Can't hold $idJob error = $err\n";
    exit 1;
}

#Signal Almigthy

oar_Tools::notifyAlmighty($remote_host,$remote_port,"Qhold");

exit 0;
