#!/usr/bin/perl
# notify Almighty

use strict;
use warnings;
use Data::Dumper;
use oar_conflib qw(init_conf dump_conf get_conf is_conf);
use Getopt::Long;
use oarversion;
use oar_Tools;

init_conf($ENV{OARCONFFILE});
my $remote_host = get_conf("SERVER_HOSTNAME");
my $remote_port = get_conf("SERVER_PORT");

my $Version;
GetOptions ("version|v" => \$Version);

if (defined($Version)){
    print("OAR version : ".oarversion::get_version()."\n");
    exit(0);
}


my $tag = "Term";
if (defined($ARGV[0])){
    $tag = $ARGV[0];
}
print("tag = $tag\n");

oar_Tools::notify_tcp_socket($remote_host,$remote_port,"$tag");

exit(0);
