#!/usr/bin/perl

use strict;
use warnings;
use Data::Dumper;
use DBI();
use oar_iolib;

sub usage(){
    print("\tusage: oarremoveresource resource_number\n");
    exit(1);
}

usage if ((@ARGV < 1) || !($ARGV[0] =~ /^\d+$/));

my $Resource = $ARGV[0];
print "Resource to remove : $Resource\n";

my $exit_code = 0;

my $base = iolib::connect();
$base->do("LOCK TABLE resources WRITE, resourceProperties WRITE,
resourceProperties_log WRITE, assignedResources WRITE, jobs WRITE, fragJobs
WRITE, events_log WRITE, events_log_hostnames WRITE, resourceStates_log WRITE");

my $resource_ref = iolib::get_resource_info($base,$Resource);
if (defined($resource_ref->{state}) && ($resource_ref->{state} eq "Dead")){
    my $sth = $base->prepare("  SELECT jobs.idJob, jobs.assignedMoldableJob
                                FROM assignedResources, jobs
                                WHERE
                                    assignedResources.idResource = $Resource
                                    AND assignedResources.idMoldableJob = jobs.assignedMoldableJob
                             ");
    $sth->execute();
    my @jobList;
    while (my @ref = $sth->fetchrow_array()) {
        push(@jobList, [$ref[0], $ref[1]]);
    }
    $sth->finish();
    foreach my $i (@jobList){
        print("\tRemove the job $i->[0], it was run on the resource $Resource\n");
        $base->do("DELETE from event_log         WHERE idJob = $i->[0]");
        $base->do("DELETE from fragJobs          WHERE fragIdJob = $i->[0]");
        $base->do("DELETE from jobs              WHERE idJob = $i->[0]");
        $base->do("DELETE from assignedResources WHERE idMoldableJob = $i->[1]");
    }
    $base->do("DELETE from assignedResources     WHERE idResource = $Resource");
    $base->do("DELETE from resourceProperties    WHERE resourceId = $Resource");
    $base->do("DELETE from resources             WHERE resourceId = $Resource");
    print("Resource $Resource removed.\n");
}else{
    print("/!\\ The state of the resource $Resource must be set to Dead before.\n");
    $exit_code = 2;
}

$base->do("UNLOCK TABLES");
iolib::disconnect($base);

exit($exit_code);
