=head1 NAME

oardel - delete job from OAR batch scheduler.

=head1 SYNOPSIS

B<oardel> [idjob]

=head1 DESCRIPTION

This command is used to delete job(s) from OAR batch scheduler. Job is designed by its job's identifier.

=head1 SEE ALSO

oarsub(1), oarstat(1), oarnodes(1), oarhold(1), oarresume(1)

=head1 COPYRIGHTS

 Copyright 2003 Laboratoire Id-Imag (http://www-id.imag.fr). This software is licensed under the GNU Library General Public License. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
