=head1 NAME

oarnodes - show occupation and state of compute nodes.

=head1 SYNOPSIS

B<oarnodes> [ -a | -s | -r numbers | -l | -h | -v ] [list of nodes] [-X | -Y | -D]

=head1 DESCRIPTION

This command is used to display the state and occupation of compute nodes in OAR batch scheduler.

=head1 OPTION

=over

=item B<-a, --all>

Show all resources with their properties.

=item B<-r, --resource>

Show only a resource with their properties.

=item B<-s, --state>

Show only resource states.

=item B<-l, --list>

Show only node list.

=item B<-D, --DUMPER>

Print result in DUMPER format.

=item B<-X, --XML>

Print result in XML format.

=item B<-Y, --YAML>

Print result in YAML format.

=item B<-v, --version>

Print OAR version number.

=item B<-h, --help>

Show help usage.


=head1 SEE ALSO

oarsub(1), oarde), oarstat(1), oarhold(1), oarresume(1)

=head1 COPYRIGHTS

 Copyright 2003 Laboratoire Id-Imag (http://www-id.imag.fr). This software is licensed under the GNU Library General Public License. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
