=head1 NAME

oarstat - show job's informations.

=head1 SYNOPSIS

B<oarstat> [[-h] | [-j job_id | --sql sql_properties][-f] | [-g "date_start,date_stop"]] [-X | -Y | -D] [-v]

=head1 DESCRIPTION

This command is used to show informations of jobs in OAR batch scheduler.

=head1 OPTIONS

=over

=item B<-f, --full>

Very detailed display.

=item B<-j, --job> job_id

Print informations from a specific job.

=item B<-g, --gantt> "date_start,date_stop"

Print history of jobs and state of resources between two dates.

=item B<--sql>

Restricts display with the SQL where clause on the table jobs (ex: "project = 'p1'")

=item B<-D, --DUMPER>

Print result in DUMPER format.

=item B<-X, --XML>

Print result in XML format.

=item B<-Y, --YAML>

Print result in YAML format.

=item B<-v, --version>

Print OAR version number.

=item B<-h, --help>

Print help message.

=back

=head1 SEE ALSO

oarsub(1), oardel(1), oarnodes(1), oarhold(1), oarresume(1)

=head1 COPYRIGHTS

 Copyright 2003 Laboratoire Id-Imag (http://www-id.imag.fr). This software is licensed under the GNU Library General Public License. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
