#!/usr/bin/perl
# kill all childs of a pid
use strict;
use Data::Dumper;
use Getopt::Long;
use oar_Tools;

Getopt::Long::Configure ("gnu_getopt");
my $usage;
GetOptions ("help|h"  => \$usage);
if ($usage){
    print <<EOS;
Usage: $0 [-h|--help] jobpid
Kill jopid children and jobpid itself
Options:
 -h, --help    show this help screen
EOS
    exit(0);
}


if (!($ARGV[0] =~ /\d+/)){
    warn("Bad arguments for oarkill\n");
    exit(1);
}

#Kill all
my @childs = oar_Tools::get_one_process_childs($ARGV[0]);

my $cmd = "sudo /bin/kill -9 @childs 2>&1 > /dev/null";
print("$cmd\n");
system("$cmd");

#for my $pid (@childs){
#    #print("sudo kill -9 $pid\n");
#    #print("OAR is killing the job with pid=$pid\n");
#    system("sudo /bin/kill -9 $pid 2>&1 > /dev/null");
#}

exit(0);

