#! /bin/sh
# postrm script for oar-restful-api
#
# see: dh_installdeb(1)

set -e
#set -x 

case "$1" in
	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	    rm -f /etc/apache2/conf.d/oar-api.conf || true
        ;;
	purge)
            #no cache to clean for the moment
            true
        ;;
  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
esac

#DEBHELPER#

exit 0
