#! /bin/sh
set -e
#set -x

. /usr/share/debconf/confmodule

MAKE="make TARGET_DIST=debian SETUP_TYPE=deb DESTDIR="
OARDIR=/usr/lib/oar

case "$1" in
    configure)
        $MAKE -C $OARDIR -f $OARDIR/Makefiles/user.mk setup
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
    
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0


