#! /bin/sh
set -e
#set -x

. /usr/share/debconf/confmodule

. /usr/lib/oar/setup/desktop-computing-cgi.sh

case "$1" in
    configure)
        adduser www-data oar || true
        desktop_computing_cgi_setup
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
    
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0


