#! /bin/sh
# postrm script for oar-common
#
# see: dh_installdeb(1)

set -e
#set -x 

OAROWNER=oar
OAROWNERGROUP=oar

case "$1" in
	remove|disappear)
	    chsh -s /bin/bash $OAROWNER
            ;;
        upgrade|failed-upgrade|abort-install|abort-upgrade)
	    ;;
	purge)

        # Remove the possible conffiles 
        for conffile in /etc/oar/oar.conf \
                        /etc/oar/oarnodesetting_ssh \
                        /etc/oar/update_cpuset_id.sh; do 
            # we mimic dpkg as closely as possible, so we remove configuration
            # files with dpkg backup extensions too:
            ### Some of the following is from Tore Anderson:
            for ext in '~' '%' .bak .dpkg-tmp .dpkg-new .dpkg-old .dpkg-dist .ucf-old .ucf-new .ucf-dist;  do
                    rm -f $conffile$ext
            done
            # remove the configuration file itself
            rm -f $conffile
            # and finally clear it out from the ucf database
            if which ucf >/dev/null; then
                    ucf --purge $conffile
            fi
            if which ucfr >/dev/null; then
                    ucfr --purge oar-common $conffile
            fi
        done

        for ext in .0 .1.gz .2.gz .3.gz .4.gz .5.gz .6.gz .7.gz; do
            rm -f /var/log/oar.log$ext
        done
        rm -f /var/log/oar.log
        rm -rf /var/run/oar
        rm -f /var/lib/oar/.bash_oar
        rm -f /var/lib/oar/.bash_profile
        rm -f /var/lib/oar/.bashrc
        rm -f /var/lib/oar/.batch_job_bashrc
        rm -rf /var/lib/oar/.ssh
        rmdir /var/lib/oar || true
        rmdir /etc/oar || true
        ;;
  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
esac

#DEBHELPER#

exit 0
