#! /bin/sh
set -e
#set -x

. /usr/share/debconf/confmodule

. /usr/lib/oar/setup/www-conf.sh
. /usr/lib/oar/setup/monika.sh
. /usr/lib/oar/setup/draw-gantt.sh

case "$1" in
    configure)
        www_conf_setup
        monika_setup
        draw_gantt_setup
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
    
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0


