#!/usr/bin/make

all: OAR-DOCUMENTATION.rst ../../../INSTALL ../../../Tools/oarsh/README
	rst2html -stg OAR-DOCUMENTATION.rst OAR-DOCUMENTATION.html
	@alsaplayer -i text /usr/share/sounds/gnibbles/reverse.wav 
	@echo Make finished
