=head1 NAME

oar-agent-daemon - OAR agent daemon

=head1 SYNOPSIS

B<oar-agent-daemon>

=head1 DESCRIPTION

oar-agent-daemon

=head1 COPYRIGHTS

 Copyright 2003-2012 LIG http://lig.imag.fr This software is licensed under the GNU General Public License Version 2 or above. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
