#!/bin/sh
# $Id: oar_epilogue,v 1.7 2004/08/24 16:10:34 neyron Exp $

# prologue arguments
# Script is run under uid of oar who is sudo
# argv[1] is the jobid
# argv[2] is the user's name
# argv[3] is the file which contains the list of nodes used
# argv[4] is the job script name if exists

exit

#Exemple for mono processor cluster
DIFFUSE_SCRIPT=~oar/oar_diffuse_script
EPILOGUE_LOCAL=~oar/oar_epilogue_local
CMD="$EPILOGUE_LOCAL $1 $2 $4"

$DIFFUSE_SCRIPT $3 $CMD

