#!/bin/sh
# $Id$
#
# This a placeholder script for OAR jobs server side prologue.
# This script is to be run on OAR server upon job start.
# This feature is activated if and only if SERVER_PROLOGUE_EXEC_FILE is set
# in OAR configuration file.

# Usage:
# Script is run under uid of oar who is sudo
# argv[1] is the jobid
# Other job information are meant to be retrieved using oarstat.

exit
