require 'webgen/plugins/tags/tags'

module Tags

  class FileMDateTag < DefaultTag

     summary "Puts bibliography on the page" 
     depends_on 'Tags'

	add_param 'bibFile','','Specifies the bibtex file to insert'

     def initialize
       super
       register_tag( 'bibliotex' )
     end

     def process_tag( tag, node, refNode )
       bibfile = get_param('bibFile')
       result = `bibtex2html --nodoc -d -r --no-header -o bib/#{bibfile} bib/#{bibfile}.bib`
       return `cat bib/#{bibfile}.html | egrep -v 'filliatr\/bibtex2html'| sed 's/<hr><p><em>This file has been generated by//' `  
     end

  end

end
