=head1 NAME

oarnotify - Multi usage command for queues and Almighty notification.

=head1 SYNOPSIS

B<oarnotify> [-e str] [-d str] [-E] [-D] [--add_queue str] [--remove_queue] [-l] [tag_to_Almighty]

=head1 DESCRIPTION

This command is used to manage scheduling queues and to notify the OAR server (Almighty).

=head1 OPTIONS

=over

=item B<-e, --enable_queue>

Active an existing queue.

=item B<-d, --disable_queue>

Inactive an existing queue.

=item B<-E, --Enable_all_queues>

Active all queues.

=item B<-D, --Disable_all_queues>

Inactive all queues.

=item B<--add_queue>

Add a new queue; syntax is name,priority,scheduler.
(ex: "name,3,oar_sched_gantt_with_timesharing")

=item B<--remove_queue>

Remove an existing queue.

=item B<-l, --list_queues>

List all queues and there status.

=item B<tag_to_Almighty>

The non exhaustive list of these tags is:
 - "Term" : ask OAR server to launch the scheduler
 - "Finaud" : ask OAR server to launch the check of empty and Suspected nodes

=back

=head1 COPYRIGHTS

 Copyright 2003 Laboratoire Id-Imag (http://www-id.imag.fr). This software is licensed under the GNU Library General Public License. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
