#!/bin/sh
# $Id$
# Detect resources on a list of nodes and print corresponding OAR commands
#set -x

OPENSSH_CMD=/usr/bin/ssh
source "$OARCONFFILE" || exit 20

OARNODES="oarnodesetting"
OARPROPERTY="oarproperty"
FILE_WITH_OAR_COMMANDS_GENERATED="/tmp/oar_resources_init.txt"

# check the file with the nodes to add
if [ -z "$1" ] || [ ! -r "$1" ]
then
    echo "Specify a file containing the list of nodes to add into OAR in argument of this command (must be readable by oar user)"
    exit 1
fi

echo "Did you configured the OAR SSH key on all the nodes? [yes/NO] "
read l ; [ "$l" != "yes" ] && exit 2

# Check output file
if [ -e "$FILE_WITH_OAR_COMMANDS_GENERATED" ]
then
    echo "Commands to run will be written into "$FILE_WITH_OAR_COMMANDS_GENERATED". Do you want to override it? [yes/NO] "
    read l ; [ "$l" != "yes" ] && exit 3
    rm $FILE_WITH_OAR_COMMANDS_GENERATED || exit 4
fi

# Add properties
echo "$OARPROPERTY -a cpu" > $FILE_WITH_OAR_COMMANDS_GENERATED
echo "$OARPROPERTY -a core" >> $FILE_WITH_OAR_COMMANDS_GENERATED
echo "$OARPROPERTY -c -a host" >> $FILE_WITH_OAR_COMMANDS_GENERATED
echo "$OARPROPERTY -a cpuset" >> $FILE_WITH_OAR_COMMANDS_GENERATED

# Init CPU id
CPU=$(oarnodes --sql true | grep 'cpu=' | awk -F ",cpu=" '{print $2}' | awk -F "," '{print $1}' | sort -r -n | head -1)
[ -z "$CPU" ] && CPU=0
# Init CORE id
CORE=$(oarnodes --sql true | grep 'core=' | awk -F ",core=" '{print $2}' | awk -F "," '{print $1}' | sort -r -n | head -1)
[ -z "$CORE" ] && CORE=0

echo
for host in $(< $1)
do
    echo -n "Checking $host ... "

    # Store stderr and redirect it to /dev/null
    exec 3>&2
    exec 2> /dev/null

    mem=$($OPENSSH_CMD $host cat /proc/meminfo | grep ^MemTotal | awk '{print $2}')

    # Get CORE info in the form
    # cpu core
    # cpu core
    # cpu core
    # ...
    if [ "`$OPENSSH_CMD $host cat /proc/cpuinfo|grep 'physical id'`" != "" ]
    then
      DATA=$($OPENSSH_CMD $host cat /proc/cpuinfo| awk '{if ($1 == "processor") cpu=$3; if ($1 == "physical" && $2 =="id") print $4 " " cpu}')
    else
      DATA=$($OPENSSH_CMD $host cat /proc/cpuinfo| awk '{if ($1 == "processor") print $3 " " $3}')
    fi

    # Restore stderr
    exec 2>&3

    if [ -z "$mem" ] || [ -z "$DATA" ]
    then
        echo "*** KO ***"
        rm $FILE_WITH_OAR_COMMANDS_GENERATED
        echo 
        echo "ERROR with node $host. Please check the ssh connection with oar user ($OPENSSH_CMD $host)..."
        exit 5
    fi

    ((mem = $mem / 1024))
    prev_cpu="-1"
    PREV_IFS=$IFS
    IFS='
'
    for i in $(echo "$DATA" | sort -g)
    do
        echo "$i"
        cpu=$(echo $i|awk '{print $1}')
        core=$(echo $i|awk '{print $2}')
        [ "$cpu" != "$prev_cpu" ] && ((CPU++))
        ((CORE++))
        prev_cpu=$cpu
        echo "oarnodesetting -a -h $host -p host=$host -p cpu=$CPU -p core=$CORE -p cpuset=$core -m mem=$mem" >> $FILE_WITH_OAR_COMMANDS_GENERATED
    done
    IFS=$PREV_IFS
    echo "OK"
done



echo
echo "If the content of '$FILE_WITH_OAR_COMMANDS_GENERATED' is OK for you then you just need to execute:"
echo "  source $FILE_WITH_OAR_COMMANDS_GENERATED"

