#!/bin/sh
# oarnodesetting_ssh: oarnodesetting SSH wrapper
# $Id$
# This script is to be called from the node via SSH so that the server performs 
# the oarnodesetting command and changes the state of the calling node.
#
# NB:
# 1- To get this script working, the oar ressource database table must have a  
# `ip' field containing the IP address for all the nodes
# 2- A dedicated SSH key may be configured to restrict the ssh call capability
# from the nodes to the server, by modifying the authorized_keys of oar on the
# serveur as follows:
# command="/usr/lib/oar/oarnodesetting_ssh" [dediacted pub key info]...
# 

IP=$(echo $SSH_CONNECTION | cut -d " " -f 1 )
[ -n "$IP" ] || exit 1
exec /usr/sbin/oarnodesetting -s Alive --sql "ip = '$IP'"
exit 1

