=head1 NAME

oargriddel - delete a reservation with all OAR jobs in the OAR_GRID system.

=head1 SYNOPSIS

B<oargriddel> [B<-h>][B<-v>][B<-V>] reservation_number

=head1 DESCRIPTION

This command is used to delete a reservation and all associated jobs on each OAR batch scheduler of the grid.


=head1 OPTIONS

=over

=item B<-h, --help>

Display help message with options and syntax.

=item B<-v, --verbose>

Turn on verbose mode.

=item B<-V, --VERSION>

Print oargrid version and exit.

=back

=head1 SEE ALSO

oargridsub(1), oargridstat(1)

=head1 COPYRIGHTS

 Copyright © 2003 Laboratoire Id-Imag (http://www-id.imag.fr). This software is licensed under the GNU Library General Public License. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
