#!/bin/bash
# $Id$

OARUSER=oar
eval CHECKLOGDIR=~$OARUSER/checklogs
if ! [ -d $CHECKLOGDIR ]; then
	echo 1>&2 "Error: Checklogs directory does not exist ($CHECKLOGDIR) !"
	exit 1
fi 
	
echo "Checklog directory is $CHECKLOGDIR"
ls $CHECKLOGDIR
