#!/bin/bash
# $Id$
# This is the shell program used with the oarsh script.
# It adds its own process in the cpuset OAR_CPUSET and launches
# the shell or the script of the user OAR_JOB_USER.

DEFAULT_SHELL=/bin/bash
XAUTH_LOCATION="/usr/bin/xauth"
OAR_SHELL_WRAPPER="/etc/oar/shell_user_wrapper.sh"

# $1 = Name of the cpuset
# $2,$3,... = PIDs to add
# Add PIDS into the cpuset $1
function add_process_to_cpuset() {
    ######################
    # CPUSET assignation #
    ###########################################################################
    CPUSET_MOUNT_POINT=$(mount -t cpuset | cut -d " " -f 3 | head -1)
    CPUSETFILE="$CPUSET_MOUNT_POINT/$1/tasks"
    
    if ( ! $(sudo test -w $CPUSETFILE) )
    then
        echo "oarsh: Cannot find cpuset file : $CPUSETFILE" 1>&2
        exit 1
    fi
    shift
    for p in $@
    do
        sudo sh -c "echo $p > $CPUSETFILE" || return 1
    done
    sudo renice 0 $@ > /dev/null 2>&1
    ###########################################################################
}

# $1 = Name of the user
# set global variable to fit to the user
function get_and_set_user_info() {
    # Get user shell (must be optimized)
    PASSWD_LINE=$(getent passwd $1)
    export SHELL=$(echo $PASSWD_LINE | cut -d : -f 7)
    if [ "$SHELL" == "" ]
    then
        echo "oarsh: No shell found for user $1." 1>&2
        exit 4
    else
        export HOME=$(echo $PASSWD_LINE | cut -d : -f 6)
        cd $HOME
    fi
}

if [ "$OAR_JOB_USER" == "" ]
then
    if [ "$SSH_CLIENT" != ""  ] && [ "$OAR_KEY" != "1" ]
    then
        echo "oarsh: The OAR_KEY environment variable is not defined and this seems to be a oar user connection." 1>&2
        echo "oarsh: See 'Important notes' part of the 'CPUSET installation' section of the OAR documentation." 1>&2
        exit 5
    fi
    # It must be oar
    if [ "$OAR_CPUSET" != "" ]
    then
        add_process_to_cpuset $OAR_CPUSET $$ $PPID || exit 2
    fi
    export SHELL=$DEFAULT_SHELL
    exec $DEFAULT_SHELL "$@"
else
    if [ "$OAR_CPUSET" == "" ]
    then
        echo "oarsh: OAR_CPUSET variable is empty; Is your sshd right configured with 'AcceptEnv OAR_CPUSET OAR_JOB_USER' on all computing nodes?" 1>&2
        exit 3
        
    fi
    add_process_to_cpuset $OAR_CPUSET $$ $PPID || exit 2
    
    #Manage display
    if [ -n "$DISPLAY" ]
    then
        if [ -x "$XAUTH_LOCATION" ]
        then
            $XAUTH_LOCATION -q extract - ${DISPLAY#localhost} | sudo -H -u $OAR_JOB_USER $XAUTH_LOCATION merge -
        fi
    fi
    #Change tty owner
    TTY=$(tty) && test -e $TTY && sudo chown $OAR_JOB_USER:oar $TTY && sudo chmod 660 $TTY
    if [ "$1" == "" ]
    then
        # Simulate initial login
        if [ -x "$OAR_SHELL_WRAPPER" ]
        then
            get_and_set_user_info $OAR_JOB_USER
            exec sudo -H -u $OAR_JOB_USER $OAR_SHELL_WRAPPER $SHELL
        else    
            exec sudo -i -u $OAR_JOB_USER
        fi
    else
        get_and_set_user_info $OAR_JOB_USER
        if [ -x "$OAR_SHELL_WRAPPER" ]
        then
            exec sudo -H -u $OAR_JOB_USER $OAR_SHELL_WRAPPER $SHELL "$@"
        else
            exec sudo -H -u $OAR_JOB_USER $SHELL "$@"
        fi
    fi
fi

