#!/bin/bash
#
# In sshd_config you must have this line :
#     AcceptEnv OAR_CPUSET SUDO_USER
# User to become is in $SUDO_USER
# $OAR_CPUSET contains the cpuset name


# Get the name of the current cpuset
function get_current_cpuset() {
    CPUSETFILE=/proc/self/cpuset

    if [ ! -r $CPUSETFILE ]
    then
        echo "[OARSH] Cannot find cpuset file : $CPUSETFILE" 1>&2
        exit 1
    fi
    echo $(< $CPUSETFILE)
}


export OAR_CPUSET=$(get_current_cpuset)

if [ "$OAR_CPUSET" == "" ] || [ "$OAR_CPUSET" == "/" ]
then
    echo "[OARSH] You are not in a OAR specific cpuset ($OAR_CPUSET) : go away!" 1>&2
    exit 2
else
    exec ssh -oSendEnv="OAR_CPUSET SUDO_USER" "$@"
fi
