LIBS=unix
PACKS=mysql
SOURCES= ../simple_cbf_mb/interval.ml helpers.ml conf.ml types.ml iolib.ml ../simple_cbf_mb/simple_cbf_mb.ml simple_cbf_mb_oar.ml
RESULT=simple_cbf_mb_oar

-include OCamlMakefile

install:  $(RESULT) 
	cp $(RESULT) /usr/lib/oar/

