#!/usr/bin/perl
# $Id$
# notify Almighty

use strict;
use warnings;
use OAR::Conf qw(init_conf dump_conf get_conf is_conf);
use Getopt::Long;
use OAR::Version;
use OAR::Tools;

sub usage() {
    my ($command) = $0 =~ /([^\/]+)$/;
    my $usage = <<EOS;
Usage:
  $command [-h] [-V] [TAG]

  Send a message tag to OAR's Almighty

Options:
  -v, --verbose             increase verbosity
  -h, --help                show this help screen
  -V, --version             print OAR version number

For OAR's scheduler queue management, see oarqueue.
EOS
  return $usage;
}

my $verbose;
Getopt::Long::Configure("gnu_getopt");
GetOptions (
            "verbose|v" => \$verbose,
            "version|V" => sub { print("OAR version : ".OAR::Version::get_version()."\n"); exit(0) },
            "help|h" => sub { print usage(); exit 0; },
           ) or die "\n".usage();

init_conf($ENV{OARCONFFILE});
my $remote_host = get_conf("SERVER_HOSTNAME");
my $remote_port = get_conf("SERVER_PORT");

my $tag = "Term";
if (defined($ARGV[0])){
    $tag = $ARGV[0];
}
if (defined($verbose)) {
    print("Sending tag: $tag\n");
}

OAR::Tools::notify_tcp_socket($remote_host,$remote_port,"$tag");

exit(0);
