=head1 NAME

Almighty - OAR server daemon.

=head1 SYNOPSIS

B<Almighty>

=head1 DESCRIPTION

This command is the OAR server daemon.

=head1 COPYRIGHTS

 Copyright 2003-2012 LIG http://lig.imag.fr This software is licensed under the GNU General Public License Version 2 or above. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
