=encoding UTF-8

=head1 NAME

oar-node - oar node services

=head1 SYNOPSIS

B<oar-node.service> oar-node's dedicated sshd

B<oar-node-script.services> oar-node's start/stop hooks script

=head1 DESCRIPTION

oar-node runs a dedicated sshd server on port 6667. It's configuration is in /etc/oar/sshd_config.

oar-node-script run the /etc/oar/oar-node-script customizable script to allow executing some commands when the oar-node service starts or stops.

=cut

