=head1 NAME

oarhold - hold a job in OAR batch scheduler.

=head1 SYNOPSIS

B<oarhold> [--array][job_ids][--sql "sql syntax"][-r][-h][-V]

=head1 DESCRIPTION

Ask OAR to not schedule jobs until oarresume command will be executed.

=head1 OPTIONS

=over

=item B<-r, --running>

Manage not only Waiting jobs but also Running one (can suspend the job)

=item B<--array> 
 
Hold array job(s) passed as parameter (all the sub-jobs of the given array job(s))
 
=item B<--sql>

Hold jobs which repond to the SQL where clause on the table jobs (ex: "project = 'p1'")

=item B<-V, --version>

Print OAR version number.

=item B<-h, --help>

Print help command message.

=back

=head1 SEE ALSO

oarsub(1), oardel(1) oarstat(1), oarnodes(1), oarresume(1)

=head1 COPYRIGHTS

 Copyright 2003-2016 Laboratoire d'Informatique de Grenoble (http://www.liglab.fr). This software is licensed under the GNU General Public License Version 2 or above. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
