=head1 NAME

oarmonitor - Launch the monitoring of a job.

=head1 SYNOPSIS

B<oarmonitor> [-h] [-f seconds] -j jobid

=head1 DESCRIPTION

This command is used to retrieve data from process on every job nodes.

=head1 OPTIONS

=over

=item B<-j, --job_id>

Job id to monitor.

=item B<-f, --frequency>

Number of seconds between each data collect (default is 60s).

=back

=head1 COPYRIGHTS

 Copyright 2003-2012 LIG http://lig.imag.fr This software is licensed under the GNU General Public License Version 2 or above. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
