=head1 NAME

oarproperty - add or remove resource properties

=head1 SYNOPSIS

B<oarproperty> [ -l | [ -a | -d ] ] [ -q ]

=head1 DESCRIPTION

This command is used to add or remove resource properties in the resource table.

=head1 OPTIONS

=over

=item B<-l, --list>

List properties.

=item B<-a NAME, --add NAME>

Add property

=item B<-c, --varchar>

Ask for a new Sql field of type VARCHAR(255) (default is integer).

=item B<-d NAME, --delete> NAME

Delete property.

=item B<-r "OLD_NAME,NEW_NAME", --rename ...>

Rename property OLD_NAME into NEW_NAME.

=item B<-q, --quiet>

Quiet mode (no extra output).

=back

=head1 COPYRIGHTS

 Copyright 2003-2012 LIG http://lig.imag.fr This software is licensed under the GNU General Public License Version 2 or above. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
