=head1 NAME

oarremoveresource - Remove a resource from the database.

=head1 SYNOPSIS

B<oarremoveresource> resource_number

=head1 DESCRIPTION

this command removes all records in the database about "resource_number".
This "resource_number" must be in the "Dead" state (see oarnodesetting).

So you will loose this resource history and jobs executed on this one.

=head1 COPYRIGHTS

 Copyright 2003-2016 Laboratoire d'Informatique de Grenoble (http://www.liglab.fr). This software is licensed under the GNU General Public License Version 2 or above. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
