=head1 NAME

oarstat - show information about jobs

=head1 SYNOPSIS

B<oarstat> [-X|-Y|-J|-D|-f] [-j jobid|--array arrayid] [--sql SQL_properties] [-u user] [--array]

B<oarstat> [--sql SQL_properties] [-u user] [--compact]

B<oarstat> [-e|-p] [-j jobid | --array arrayid]

B<oarstat> -s [-X|-Y|-J|-D] -j jobid

B<oarstat> [-X|-Y|-J|-D] --gantt "YYYY-MM-DD hh:mm:ss, YYYY-MM-DD hh:mm:ss"

B<oarstat> --accounting "YYYY-MM-DD, YYYY-MM-DD"

=head1 DESCRIPTION

This command is used to show information of jobs in OAR batch scheduler.

=head1 OPTIONS

=over

=item B<-f, --full>

Very detailed display.

=item B<-j, --job> job_id

Print information from a specific job.

=item B<-e, --events>

Print job events only.

=item B<-p, --properties>

Print job properties in the same format as in the $OAR_RESOURCE_PROPERTIES_FILE file on the nodes.

=item B<-s, --state>

Print only the state of a specified job. It makes a minimal query to the database. It is optimized to allow scripting for example. Must be used with -j.

=item B<-u, --user> [login]

Print information for the current user or the one given.
If used with --accounting, print a more detailed accounting report for the user.

=item B<--array> [array_id]
 
Toggle the visualization of array information on.  If an array_id is provided, print information relative to the subjobs of the given array job.

=item B<-c, --compact>

Prints only one line for all the jobs belonging to a same array. The id is replaced by <N>@<id> where "N" is the number of jobs inside the array and "id" is the id of the array. The state is not relevant for an array of jobs (as some jobs may be waiting while others are running for example), so the state column always shows a dash.

=item B<--sql>

Restricts display with the SQL where clause on the table jobs (ex: "project = 'p1'")

=item B<-D, --DUMPER>

Print result in DUMPER format.

=item B<-X, --XML>

Print result in XML format.

=item B<-Y, --YAML>

Print result in YAML format.

=item B<-J, --JSON>

Print result in JSON format.

=item B<-g, --gantt> "date_start,date_stop"

Print history of jobs and state of resources between two dates like "2006-03-30 13:49:27, 2006-04-30 13:49:27"

=item B<--accounting> "date_start,date_stop"

Shows accounting information between two dates like "2006-03-30, 2006-04-30".
 If --user is also used, more details are shown for this particular user.
 Warning: the accounting table must be up to date. The update must be done at superuser level with the oaraccounting command. 

=item B<-V, --version>

Print OAR version number.

=item B<-h, --help>

Print help message.

=back

=head1 SEE ALSO

oarprint(1), oarsub(1), oardel(1), oarnodes(1), oarhold(1), oarresume(1)

=head1 COPYRIGHTS

 Copyright 2008 Laboratoire d'Informatique de Grenoble (http://www.liglab.fr). This software is licensed under the GNU Library General Public License. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
